---
kind: pipeline
name: testing

steps:
  - name: test
    pull: always
    image: golang:alpine
    commands:
      - apk add make
      - make test
      - make coverage

  - name: codecov
    image: plugins/codecov
    settings:
      token: b230c554-0e2a-4ac0-b5bd-f0cd3be05592

trigger:
  branch:
    - master
