---
kind: pipeline
name: default

steps:
- name: build
  image: golang:alpine
  commands:
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
  - ./app
- name: publish
  image: plugins/docker
  settings:
    auto_tags: true
    dockerfile: Dockerfile
    repo: lddsb/drone-demo
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password