---
kind: pipeline
name: default

steps:
  - name: codecov
    image: plugins/codecov
    settings:
      token: b230c554-0e2a-4ac0-b5bd-f0cd3be05592
      requred: true
      files:
        - test.py
        - __ini__.py
      paths:
        - ./
        - awesome
